"""Structural types for the repositories (one per aggregate).

Services that take a repository as a parameter type it with these Protocols, so they depend on
the shape rather than the SQLAlchemy class; tests may pass any object with the same methods.
The ``TYPE_CHECKING`` block at the end makes pyright prove every concrete repository conforms.
"""

import builtins
import datetime as dt
from collections.abc import Iterable, Mapping, Sequence
from typing import TYPE_CHECKING, Any, Protocol

from app.repositories.models import (
    AiAudit,
    ChartAsset,
    CharterItem,
    CheckIn,
    Domain,
    EntityAlias,
    FeedEvent,
    Holiday,
    HolidayRegion,
    HourOverride,
    LeaveDay,
    Milestone,
    Note,
    Project,
    ReadinessItem,
    RemiEvent,
    Rotation,
    Routine,
    RoutineChecklistItem,
    RoutineRun,
    RoutineRunTick,
    Settings,
    Task,
    TextbookBlock,
    TextbookPage,
    TextbookSection,
)


class SettingsRepo(Protocol):
    def get(self) -> Settings: ...
    def update(self, **fields: Any) -> Settings: ...
    def update_from(self, fields: Mapping[str, Any]) -> Settings: ...
    def reset(self) -> Settings: ...
    def is_setup_complete(self) -> bool: ...


class HolidayRepo(Protocol):
    def list(
        self,
        region: HolidayRegion,
        frm: dt.date | None = None,
        to: dt.date | None = None,
        *,
        include_suppressed: bool = True,
    ) -> builtins.list[Holiday]: ...
    def effective(self, region: HolidayRegion, frm: dt.date, to: dt.date) -> dict[dt.date, str]: ...
    def get(self, region: HolidayRegion, day: dt.date) -> Holiday | None: ...
    def covered_years(self, region: HolidayRegion) -> dict[int, str]: ...
    def replace_generated_year(
        self,
        region: HolidayRegion,
        year: int,
        generated: Mapping[dt.date, str],
        *,
        package_version: str,
        generated_at: dt.datetime,
    ) -> int: ...
    def add_manual(self, region: HolidayRegion, day: dt.date, name: str) -> Holiday: ...
    def suppress(self, row: Holiday) -> None: ...
    def delete(self, row: Holiday) -> None: ...


class LeaveRepo(Protocol):
    def list(
        self, frm: dt.date | None = None, to: dt.date | None = None
    ) -> builtins.list[LeaveDay]: ...
    def as_mapping(
        self, frm: dt.date | None = None, to: dt.date | None = None
    ) -> dict[dt.date, float | None]: ...
    def get(self, day: dt.date) -> LeaveDay | None: ...
    def put(self, day: dt.date, hours: float | None, note: str) -> LeaveDay: ...
    def delete(self, row: LeaveDay) -> None: ...


class ProjectRepo(Protocol):
    def get(self, project_id: str, *, full: bool = True) -> Project | None: ...
    def require(self, project_id: str, *, full: bool = True) -> Project: ...
    def list(
        self, domain: Domain | None = None, *, full: bool = True
    ) -> builtins.list[Project]: ...
    def ids(self) -> set[str]: ...
    def exists(self, project_id: str) -> bool: ...
    def count(self, domain: Domain | None = None) -> int: ...
    def add(self, project: Project) -> Project: ...
    def delete(self, project: Project) -> None: ...
    def next_sort_order(self, domain: Domain) -> int: ...
    def get_task(self, task_id: str) -> Task | None: ...
    def get_milestone(self, milestone_id: str) -> Milestone | None: ...
    def get_charter_item(self, item_id: str) -> CharterItem | None: ...
    def get_readiness_item(self, item_id: str) -> ReadinessItem | None: ...
    def get_checkin(self, checkin_id: str) -> CheckIn | None: ...
    def set_override(self, project_id: str, day: dt.date, hours: float) -> HourOverride: ...
    def clear_override(self, project_id: str, day: dt.date) -> bool: ...
    def set_bau_day_hours(self, project_id: str, rules: Mapping[str, float]) -> None: ...
    def snapshots(self, project_id: str) -> builtins.list[CheckIn]: ...


class RoutineRepo(Protocol):
    def list(self) -> builtins.list[Routine]: ...
    def get(self, routine_id: str) -> Routine | None: ...
    def require(self, routine_id: str) -> Routine: ...
    def exists(self, routine_id: str) -> bool: ...
    def count(self) -> int: ...
    def add(self, routine: Routine) -> Routine: ...
    def delete(self, routine: Routine) -> None: ...
    def next_sort_order(self) -> int: ...
    def get_checklist_item(self, item_id: str) -> RoutineChecklistItem | None: ...
    def runs_between(
        self, frm: dt.date, to: dt.date, routine_id: str | None = None
    ) -> builtins.list[RoutineRun]: ...
    def ticks_between(
        self, frm: dt.date, to: dt.date, routine_id: str | None = None
    ) -> builtins.list[RoutineRunTick]: ...
    def get_run(self, routine_id: str, day: dt.date) -> RoutineRun | None: ...
    def upsert_run(
        self,
        routine_id: str,
        day: dt.date,
        completed_on: dt.date | None,
        completed_at: dt.datetime | None,
    ) -> RoutineRun: ...
    def set_tick(
        self, routine_id: str, day: dt.date, item_id: str, done: bool, at: dt.datetime
    ) -> bool: ...
    def set_all_ticks(
        self, routine_id: str, day: dt.date, item_ids: Iterable[str], done: bool, at: dt.datetime
    ) -> int: ...


class RotationRepo(Protocol):
    def get_active(self) -> Rotation | None: ...
    def add(self, rotation: Rotation) -> Rotation: ...


class NoteRepo(Protocol):
    def get(self, note_id: str) -> Note | None: ...
    def list_day(self, day: dt.date) -> builtins.list[Note]: ...
    def list_between(
        self, frm: dt.date | None = None, to: dt.date | None = None
    ) -> builtins.list[Note]: ...
    def day_counts(
        self, frm: dt.date | None = None, to: dt.date | None = None
    ) -> dict[dt.date, int]: ...
    def count_total(self) -> int: ...
    def count_days(self) -> int: ...
    def count_on(self, day: dt.date) -> int: ...
    def next_seq(self, day: dt.date) -> int: ...
    def add(self, note: Note) -> Note: ...
    def delete(self, note: Note) -> None: ...


class AliasRepo(Protocol):
    def list(self) -> builtins.list[EntityAlias]: ...
    def get(self, alias_id: str) -> EntityAlias | None: ...
    def by_entity(self) -> dict[str, builtins.list[str]]: ...
    def delete(self, row: EntityAlias) -> None: ...


class FeedRepo(Protocol):
    def add(self, item: FeedEvent) -> FeedEvent: ...
    def list(self, limit: int = 50, before: str | None = None) -> builtins.list[FeedEvent]: ...


class EventRepo(Protocol):
    def latest_seq(self) -> int: ...
    def latest_plan_seq(self) -> int: ...
    def count(self) -> int: ...
    def list(self, since_seq: int = 0, limit: int = 100) -> builtins.list[RemiEvent]: ...
    def for_ref(self, ref_type: str, ref_id: str, limit: int = 100) -> builtins.list[RemiEvent]: ...


class TextbookRepo(Protocol):
    def sections(self) -> builtins.list[TextbookSection]: ...
    def get_section(self, section_id: str) -> TextbookSection | None: ...
    def pages(self) -> builtins.list[TextbookPage]: ...
    def get_page(self, page_id: str, *, with_blocks: bool = True) -> TextbookPage | None: ...
    def count_pages(self) -> int: ...
    def count_chart_blocks(self) -> int: ...
    def section_is_empty(self, section_id: str) -> bool: ...
    def replace_blocks(
        self, page: TextbookPage, blocks: Sequence[TextbookBlock], base_version: int
    ) -> TextbookPage: ...
    def search(self, query: str, limit: int = 50) -> builtins.list[TextbookPage]: ...


class ChartAssetRepo(Protocol):
    def get(self, asset_id: str) -> ChartAsset | None: ...
    def get_by_hash(self, content_hash: str) -> ChartAsset | None: ...
    def add(self, asset: ChartAsset) -> ChartAsset: ...
    def unreferenced(self) -> builtins.list[ChartAsset]: ...


class AiAuditRepo(Protocol):
    def add(self, row: AiAudit) -> AiAudit: ...
    def get(self, audit_id: str) -> AiAudit | None: ...
    def list(self, limit: int = 50, before: str | None = None) -> builtins.list[AiAudit]: ...
    def purge_before(self, cutoff: dt.datetime) -> int: ...


if TYPE_CHECKING:  # pragma: no cover - static conformance checks only
    from app.repositories.ai_audit_repo import AiAuditRepository
    from app.repositories.alias_repo import AliasRepository
    from app.repositories.chart_asset_repo import ChartAssetRepository
    from app.repositories.event_repo import EventRepository
    from app.repositories.feed_repo import FeedRepository
    from app.repositories.holiday_repo import HolidayRepository, LeaveRepository
    from app.repositories.note_repo import NoteRepository
    from app.repositories.project_repo import ProjectRepository
    from app.repositories.rotation_repo import RotationRepository
    from app.repositories.routine_repo import RoutineRepository
    from app.repositories.settings_repo import SettingsRepository
    from app.repositories.textbook_repo import TextbookRepository

    def check_repository_conformance(
        settings: SettingsRepository,
        holidays: HolidayRepository,
        leave: LeaveRepository,
        projects: ProjectRepository,
        routines: RoutineRepository,
        rotation: RotationRepository,
        notes: NoteRepository,
        aliases: AliasRepository,
        feed: FeedRepository,
        events: EventRepository,
        textbook: TextbookRepository,
        charts: ChartAssetRepository,
        audit: AiAuditRepository,
    ) -> Sequence[object]:
        checked: tuple[
            SettingsRepo,
            HolidayRepo,
            LeaveRepo,
            ProjectRepo,
            RoutineRepo,
            RotationRepo,
            NoteRepo,
            AliasRepo,
            FeedRepo,
            EventRepo,
            TextbookRepo,
            ChartAssetRepo,
            AiAuditRepo,
        ] = (
            settings,
            holidays,
            leave,
            projects,
            routines,
            rotation,
            notes,
            aliases,
            feed,
            events,
            textbook,
            charts,
            audit,
        )
        return checked
