"""SQLAlchemy 2 ORM tables. Importing this package registers every table on ``Base.metadata``."""

from remi.repositories.models.ai import AiAudit
from remi.repositories.models.base import (
    DOMAINS,
    HOLIDAY_REGIONS,
    NAMING_CONVENTION,
    Base,
    CreatedAt,
    Domain,
    HolidayRegion,
    JSONDict,
    JSONList,
    Timestamps,
    UTCDateTime,
    UUIDPk,
    format_utc,
    parse_utc,
)
from remi.repositories.models.calendar import (
    HOLIDAY_SOURCES,
    Holiday,
    HolidaySource,
    HolidayYear,
    LeaveDay,
)
from remi.repositories.models.events import ACTORS, EVENT_SCHEMA_VERSION, Actor, RemiEvent
from remi.repositories.models.feed import FeedEvent
from remi.repositories.models.notes import EntityAlias, Note
from remi.repositories.models.project import (
    CHARTER_LISTS,
    CHECKIN_SOURCES,
    MILESTONE_HORIZONS,
    PHASES,
    CharterItem,
    CharterList,
    CheckIn,
    CheckInSource,
    Checklist,
    ChecklistItem,
    HourOverride,
    Milestone,
    MilestoneHorizon,
    Project,
    ProjectBauDayHours,
    ReadinessItem,
    Risk,
    ScopeChange,
    Task,
)
from remi.repositories.models.rotation import (
    ROTATION_PASSES,
    Rotation,
    RotationPass,
    RotationSegment,
)
from remi.repositories.models.routine import (
    ROUTINE_KINDS,
    STAGES,
    Routine,
    RoutineChecklistItem,
    RoutineKind,
    RoutineRun,
    RoutineRunTick,
)
from remi.repositories.models.settings import (
    AI_PROVIDERS,
    MOTION_PREFERENCES,
    MOVE_TAPERS,
    SETTINGS_ID,
    AIProvider,
    MotionPreference,
    MoveTaper,
    Settings,
)
from remi.repositories.models.textbook import (
    BLOCK_TYPES,
    DEFAULT_CHART_HEIGHT,
    BlockType,
    ChartAsset,
    TextbookBlock,
    TextbookPage,
    TextbookSection,
)

metadata = Base.metadata

__all__ = [
    "ACTORS",
    "AI_PROVIDERS",
    "BLOCK_TYPES",
    "CHARTER_LISTS",
    "CHECKIN_SOURCES",
    "DEFAULT_CHART_HEIGHT",
    "DOMAINS",
    "EVENT_SCHEMA_VERSION",
    "HOLIDAY_REGIONS",
    "HOLIDAY_SOURCES",
    "MILESTONE_HORIZONS",
    "MOTION_PREFERENCES",
    "MOVE_TAPERS",
    "NAMING_CONVENTION",
    "PHASES",
    "ROTATION_PASSES",
    "ROUTINE_KINDS",
    "SETTINGS_ID",
    "STAGES",
    "AIProvider",
    "Actor",
    "AiAudit",
    "Base",
    "BlockType",
    "ChartAsset",
    "CharterItem",
    "CharterList",
    "CheckIn",
    "CheckInSource",
    "Checklist",
    "ChecklistItem",
    "CreatedAt",
    "Domain",
    "EntityAlias",
    "FeedEvent",
    "Holiday",
    "HolidayRegion",
    "HolidaySource",
    "HolidayYear",
    "HourOverride",
    "JSONDict",
    "JSONList",
    "LeaveDay",
    "Milestone",
    "MilestoneHorizon",
    "MotionPreference",
    "MoveTaper",
    "Note",
    "Project",
    "ProjectBauDayHours",
    "ReadinessItem",
    "RemiEvent",
    "Risk",
    "Rotation",
    "RotationPass",
    "RotationSegment",
    "Routine",
    "RoutineChecklistItem",
    "RoutineKind",
    "RoutineRun",
    "RoutineRunTick",
    "ScopeChange",
    "Settings",
    "Task",
    "TextbookBlock",
    "TextbookPage",
    "TextbookSection",
    "Timestamps",
    "UTCDateTime",
    "UUIDPk",
    "format_utc",
    "metadata",
    "parse_utc",
]
