"""Public holidays, generated offline by the ``holidays`` package (England and Wales, South Africa).

Rules (so the stored calendar matches the prototype's):

- Names are normalised: ``" (observed)"`` becomes ``" (substitute)"`` (``Boxing Day
  (substitute)`` on Mon 28 Dec 2026).
- Holidays that fall on a Saturday or Sunday are **not** stored: those days are plain weekend
  days (Sat 26 Dec 2026 is a weekend, not "Boxing Day"). The weekday substitute is stored.
- Generation is per (region, year) and recorded in ``holiday_years`` with the package version.
  A year generated by a different package version is regenerated (current and future years
  only); manual rows and suppressed (user-removed) rows are always kept.

``ensure_years_in`` writes into the caller's unit of work (no event of its own), e.g. first-run
setup. ``ensure_years`` opens its own short ``system`` unit of work when anything is missing
(the lazy extension reads use), recording one ``holidays.generated`` event.
"""

import datetime as dt
from collections.abc import Iterable, Mapping
from typing import Final

import holidays as holidays_pkg

from remi.core.clock import Clock
from remi.core.errors import OutOfRange
from remi.core.uow import UnitOfWork, UnitOfWorkFactory, ref
from remi.repositories.holiday_repo import HolidayRepository
from remi.repositories.models import HolidayRegion
from remi.repositories.registry import HOLIDAYS

MIN_YEAR: Final = 1990
MAX_YEAR: Final = 2100
"""The supported calendar (``OUT_OF_RANGE`` outside it)."""

REGION_LABELS: Final[Mapping[HolidayRegion, str]] = {
    "GB-ENG": "England and Wales",
    "ZA": "South Africa",
}
_PACKAGE_ARGS: Final[Mapping[HolidayRegion, tuple[str, str | None]]] = {
    "GB-ENG": ("GB", "ENG"),
    "ZA": ("ZA", None),
}
_OBSERVED: Final = " (observed)"
_SUBSTITUTE: Final = " (substitute)"


def package_version() -> str:
    """The installed ``holidays`` version (stored per generated year)."""
    return str(getattr(holidays_pkg, "__version__", "unknown"))


def normalise_name(name: str) -> str:
    """The prototype's wording: ``Boxing Day (observed)`` -> ``Boxing Day (substitute)``."""
    return name.replace(_OBSERVED, _SUBSTITUTE)


def check_year(year: int) -> None:
    if not MIN_YEAR <= year <= MAX_YEAR:
        msg = f"Remi's calendar covers {MIN_YEAR} to {MAX_YEAR}."
        raise OutOfRange(msg)


def generate(region: HolidayRegion, years: Iterable[int]) -> dict[dt.date, str]:
    """Weekday holidays for ``region`` in ``years``, with normalised names. Pure and offline."""
    wanted = sorted(set(years))
    for year in wanted:
        check_year(year)
    if not wanted:
        return {}
    country, subdiv = _PACKAGE_ARGS[region]
    generated = holidays_pkg.country_holidays(country, subdiv=subdiv, years=wanted)
    out: dict[dt.date, str] = {}
    for day, name in sorted(generated.items()):
        if day.isoweekday() > 5:
            continue
        out[day] = normalise_name(str(name))
    return out


def years_to_generate(
    repo: HolidayRepository, region: HolidayRegion, years: Iterable[int], today: dt.date
) -> list[int]:
    """Years that are missing, or were generated by another package version (current and
    future years only)."""
    covered = repo.covered_years(region)
    version = package_version()
    out: list[int] = []
    for year in sorted(set(years)):
        check_year(year)
        stored = covered.get(year)
        if stored is None or (stored != version and year >= today.year):
            out.append(year)
    return out


def ensure_years_in(
    uow: UnitOfWork, region: HolidayRegion, years: Iterable[int], *, today: dt.date
) -> list[int]:
    """Generate the missing (or stale) ``years`` into ``uow``'s transaction. No event of its
    own: the caller records one. Returns the years generated."""
    repo = uow.repo(HOLIDAYS)
    todo = years_to_generate(repo, region, years, today)
    if not todo:
        return []
    now = uow.clock.now()
    version = package_version()
    rows = generate(region, todo)
    for year in todo:
        in_year = {d: n for d, n in rows.items() if d.year == year}
        repo.replace_generated_year(
            region, year, in_year, package_version=version, generated_at=now
        )
    return todo


def missing_years(
    uow_factory: UnitOfWorkFactory, region: HolidayRegion, years: Iterable[int], today: dt.date
) -> list[int]:
    with uow_factory.read() as uow:
        return years_to_generate(uow.repo(HOLIDAYS), region, years, today)


def ensure_years(
    uow_factory: UnitOfWorkFactory, clock: Clock, region: HolidayRegion, years: Iterable[int]
) -> list[int]:
    """Make sure ``years`` are generated, in a short ``system`` unit of work if needed.

    Returns the years generated (empty when everything was already there, in which case
    nothing is written).
    """
    wanted = sorted(set(years))
    today = clock.today()
    if not missing_years(uow_factory, region, wanted, today):
        return []
    with uow_factory("system") as uow:
        done = ensure_years_in(uow, region, wanted, today=today)
        if done:
            uow.record(
                "holidays.generated",
                [ref("holidays", region)],
                {"region": region, "years": done, "packageVersion": package_version()},
            )
    return done


def year_span(first: int, last: int) -> range:
    return range(first, last + 1)
