// Generated by frontend/scripts/subset-icons.sh. Do not edit by hand.
// Source: material-symbols-outlined.woff2. Material Symbols is Apache-2.0 (Google).

/** Every icon in src/assets/fonts/material-symbols-remi.woff2, with its codepoint. */
export const ICON_CODEPOINTS = {
  add: 0xe145,
  arrow_forward: 0xe5c8,
  calendar_month: 0xebcc,
  check: 0xe5ca,
  chevron_left: 0xe408,
  chevron_right: 0xe409,
  close: 0xe14c,
  close_fullscreen: 0xf1cf,
  delete: 0xe872,
  description: 0xe873,
  drag_indicator: 0xe945,
  edit_note: 0xe745,
  functions: 0xe24a,
  home: 0xe88a,
  horizontal_rule: 0xf108,
  insert_chart: 0xe24b,
  left_panel_close: 0xf717,
  left_panel_open: 0xf716,
  north_east: 0xf1e1,
  notes: 0xe26c,
  open_in_full: 0xf1ce,
  repeat: 0xe040,
  right_panel_close: 0xf705,
  right_panel_open: 0xf704,
  search: 0xe8b6,
  settings: 0xe8b8,
  stacks: 0xf500,
  title: 0xe264,
  today: 0xe8df,
  tune: 0xe429,
  unfold_more: 0xe5d7,
  upload_file: 0xe9fc,
  view_timeline: 0xeb85,
} as const;

export type IconName = keyof typeof ICON_CODEPOINTS;
